version: "3.9"
services:
  fastapi:
    build: ./fastapi
    env_file:
      - ./fastapi/.env
    volumes:
      - ./fastapi:/app
      - ${SOURCE_REPOS_PATH}:/source-repos
    ports:
      - 8000:8000
  nextjs:
    build: ./nextjs
    volumes:
      - ./nextjs:/usr/src/app
    ports:
      - 3000:3000
