version: "3.9"
services:
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi/app:/app
    ports:
      - 8000:8000
  nextjs:
    build: ./nextjs
    volumes:
      - ./nextjs:/usr/src/app
    ports:
      - 3000:3000
